# Generated by Django 4.2.3 on 2023-07-18 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='filename',
            field=models.CharField(default=django.utils.timezone.now, help_text='filename', max_length=50),
            preserve_default=False,
        ),
    ]
