# Generated by Django 4.2.3 on 2023-07-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_user_table_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='filename',
            field=models.ImageField(upload_to='static/uploads'),
        ),
    ]
